### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 334: invalid start byte

### ISSUE THREAD

**Issue by JennyVVV** [NVlabs/splatnet#11]
Hi, when I try to run the command: SKIP_TRAIN=1 ./exp/facade3d/train_test.sh, it has problem as title:
Traceback (most recent call last):
  File "/home/ryxu/splatnet/exp/facade3d/../../splatnet/semseg3d/test.py", line 211, in <module>
    args.dataset_params, save_dir, save_prefix, args.cpu)
  File "/home/ryxu/splatnet/exp/facade3d/../../splatnet/semseg3d/test.py", line 96, in semseg_test
    data, xyz, norms = dataset_facade.points(dims=input_dims+',x_y_z,nx_ny_nz', **dataset_params)
  File "/home/ryxu/splatnet/splatnet/dataset/dataset_facade.py", line 90, in points
    pcl_data = np.loadtxt(pcl_test_path, skiprows=15)
  File "/home/ryxu/miniconda3/envs/caffe/lib/python3.5/site-packages/numpy/lib/npyio.py", line 880, in loadtxt
    next(fh)
  File "/home/ryxu/miniconda3/envs/caffe/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 334: invalid start byte

It maybe the decode problem, how to solve this problem in this splatnet project? Thanks.

**Comment by suhangpro** [comment]
Were the data files generated as instructed [here](https://github.com/NVlabs/splatnet/tree/master/data#ruemonge428) using the same machine? There is no specified codec when generating the data files, but I would assume loading the files written by np.savetxt() on the same machines/system with np.loadtxt() should work ...
